### ISSUE TITLE
extract_attributes.py does not work

### ISSUE THREAD

**Issue by zhenyuZ-HUST** [gtzheng/FewSTAB#1]
I don't see a description for the running environment. When running extract_attributes.py, it shows "Unable to create tensor". So, could you please provide test_vit-gpt2_captions.csv and test_vit-gpt2_attribute_embeds.pickle for few-shot datasets?

**Comment by gtzheng** [comment]
Thank you for your interest in our work. You can find `test_vit-gpt2_captions.csv` and  `test_vit-gpt2_attribute_embeds.pickle` [here](https://drive.google.com/drive/folders/11p_PIhnGRBdPJqVvBpQD6rEwBybFVfZu?usp=sharing).
